"use client";
import { FormEvent, useEffect, useState } from "react";
import { api } from "../lib/api";

type Organization={id:string;name:string;slug:string;createdAt:string};
type Member={id:string;name:string;email:string;role:"owner"|"manager"|"qa";createdAt:string};

export default function OrganizationPage(){
  const [organization,setOrganization]=useState<Organization|null>(null);const [members,setMembers]=useState<Member[]>([]);const [message,setMessage]=useState("Loading organization…");const [busy,setBusy]=useState(false);const [canEdit,setCanEdit]=useState(false);
  async function load(){try{const [workspace,people]=await Promise.all([api<Organization>("/organization"),api<Member[]>("/organization/members")]);setOrganization(workspace);setMembers(people);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Could not load organization");}}
  useEffect(()=>{try{const currentUser=JSON.parse(localStorage.getItem("loopclose_user")||"{}") as {role?:string};setCanEdit(currentUser.role==="owner");}catch{setCanEdit(false);}load();},[]);
  async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const name=String(new FormData(event.currentTarget).get("name")||"");try{const workspace=await api<Organization>("/organization",{method:"PATCH",body:JSON.stringify({name})});setOrganization(workspace);setMessage("Organization name updated.");}catch(error){setMessage(error instanceof Error?error.message:"Could not update organization");}finally{setBusy(false);}}
  return <main className="flow-page"><div className="flow-wrap"><nav className="flow-nav"><a className="flow-brand" href="/"><span className="brand-mark">L</span><span>LoopClose</span></a><a href="/">← Dashboard</a></nav><div className="flow-heading"><h1>Organization</h1><p>Manage your workspace identity and see who has access.</p></div><form className="form-card organization-card" onSubmit={update}><label className="field">Organization name<input name="name" key={organization?.name} defaultValue={organization?.name||""} required minLength={2} disabled={!canEdit}/></label><div className="organization-meta"><span>Workspace ID</span><code>{organization?.slug||"—"}</code></div><div className="form-actions"><span className={`form-message ${message&&!organization?"error":""}`}>{message||(canEdit?"Only organization owners can change this name.":"Ask an organization owner to make changes.")}</span>{canEdit?<button className="primary-button" disabled={busy}>{busy?"Saving…":"Save changes"}</button>:null}</div></form><section className="members-section"><div className="panel-head"><div><h2>Members</h2><p>People who can access this organization’s data</p></div><span className="data-count">{members.length} total</span></div><div className="list-card">{members.map(member=><article className="member-row" key={member.id}><span className="member-avatar">{member.name.split(" ").map(value=>value[0]).slice(0,2).join("")}</span><div><strong>{member.name}</strong><small>{member.email}</small></div><span className={`role-badge ${member.role}`}>{member.role}</span></article>)}{!members.length?<div className="empty-state">{message||"No members yet."}</div>:null}</div></section></div></main>;
}
