"use client";
import { FormEvent, useState } from "react";
import { api } from "../lib/api";

export default function Login(){
  const [mode,setMode]=useState<"login"|"register">("login"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const values=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api<{accessToken:string}>(`/auth/${mode}`,{method:"POST",body:JSON.stringify(values)});localStorage.setItem("loopclose_token",result.accessToken);location.href="/";}catch(error){setMessage(error instanceof Error?error.message:"Could not sign in");}finally{setBusy(false);}}
  return <main className="flow-page"><div className="flow-wrap" style={{maxWidth:440}}><nav className="flow-nav"><a className="flow-brand" href="/">LoopClose</a><a href="#" onClick={e=>{e.preventDefault();setMode(mode==="login"?"register":"login")}}>{mode==="login"?"Create an account":"I have an account"}</a></nav><div className="flow-heading"><h1>{mode==="login"?"Welcome back":"Create your workspace"}</h1><p>{mode==="login"?"Sign in to review your team’s commitments.":"Start turning meeting promises into verified outcomes."}</p></div><form className="form-card" onSubmit={submit}>{mode==="register"&&<label className="field">Full name<input name="name" required minLength={2} autoComplete="name" /></label>}<label className="field">Work email<input type="email" name="email" required autoComplete="email" /></label><label className="field">Password<input type="password" name="password" required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"}/></label><div className="form-actions"><span className={`form-message ${message?"error":""}`}>{message||"Your session is protected with a signed token."}</span><button className="primary-button" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></div></form></div></main>;
}
